### ISSUE TITLE
Limitation of functions as keys?

### ISSUE THREAD

**Issue by tdeenes** [randy3k/collections#10]
MRE:
```r
d <- dict()
d$set(function(x) 1L, TRUE) # OK

fun <- function(x) x
d$set(fun, TRUE) # error
# Error in base::serialize(object, connection = NULL, ascii = ascii, version = serializeVersion) :  object 'x' not found
# Error in d$set(fun, TRUE) : cannot compute digest of the key

sfun <- serialize(fun, NULL)
d$set(sfun, TRUE) # OK
```

The documentation of `dict` states:
> key: scalar character, environment or function

It seems there is a serious limitation on which functions can be used as keys. Is this intentional, but (currently) undocumented?

**Comment by randy3k** [comment]
It seems to be a bug. Thank you for reporting.

**Comment by randy3k** [comment]
~~As a workaround for now, add curly braces around the `{x}`~~


```
fun <- function(x) {x}
d$set(fun, TRUE)
```

EDIT: it doesn't actually work..

**Comment by randy3k** [comment]
The master branch should fix it :)

**Comment by tdeenes** [comment]
Confimed :) That was quick, thank you!

**Comment by randy3k** [comment]
0.3.3 is on its way to CRAN.
