### ISSUE TITLE
Huge speed difference depending on key type

### ISSUE THREAD

**Issue by tdeenes** [randy3k/collections#11]
Is it expected that non-environment and non-character keys are approx. 25x slower to get? I assume the reason can be that non-environment/non-character keys must be serialized first (see the script below). 

```r
library(collections)

env <- new.env(parent = emptyenv())
num <- 1
int <- 1L
char <- "a"
bool <- TRUE

d_env <- dict()$set(env, NULL)
d_num <- dict()$set(num, NULL)
d_int <- dict()$set(int, NULL)
d_char <- dict()$set(char, NULL)
d_bool <- dict()$set(bool, NULL)
d_ser_int <- dict()$set(serialize(int, NULL), NULL)

microbenchmark::microbenchmark(
  d_env$get(env),
  d_num$get(num),
  d_int$get(int),
  d_char$get(char),
  d_bool$get(bool)
)
# Unit: microseconds
#        expr    min      lq     mean  median      uq     max neval
#         env  1.299  1.9655  2.14228  2.2315  2.3325   5.150   100
#         num 40.160 41.2545 44.06497 42.2385 44.0770 141.945   100
#         int 39.036 40.9910 43.23154 42.1640 43.9230  70.183   100
#        char  1.051  1.5435  1.83238  1.9385  2.0555   4.794   100
#        bool 39.232 40.8540 43.58119 41.7245 44.5625  64.041   100
#  serial_int 43.176 44.7480 47.04926 45.9635 47.9180  66.670   100
```

**Comment by randy3k** [comment]
You are right. Internally, we depend on `digest::digest` to serialize
non-char objects first. It may be possible to implement our own hashing algorithm but it won’t be happening anytime soon.

**Comment by randy3k** [comment]
For environments, they are not serialized. Instead, their memory addresses are used as hashes.

**Comment by tdeenes** [comment]
Have you tried using the "spookyhash" algo of the digest package? Or do you know the **fastdigest** package?

For small objects, `fastdigest::fastdigest` is much faster then the alternatives. For larger objects, `digest::digest(.., algo = "spookyhash")` is the winner with a slight margin, and both are tremendously faster then the md5 (or other) algos. 

```r
library(digest)
library(fastdigest)
library(microbenchmark)

small <- 1
medium <- runif(1e5)
large <- runif(1e7)

microbenchmark(
  small_md5 = digest(small),
  small_sh = digest(small, algo = "spookyhash"),
  small_sh_fastd = fastdigest(small),
  medium_md5 = digest(medium), ## very slow...
  medium_sh = digest(medium, algo = "spookyhash"),
  medium_sh_fastd = fastdigest(medium),
  #large_md5 = digest(large), ## this is way too slow...
  large_sh = digest(large, algo = "spookyhash"),
  large_sh_fastd = fastdigest(large),
  times = 1000
)
# Unit: microseconds
#             expr      min        lq        mean    median         uq       max
#        small_md5   29.570   37.5785    55.52737   45.1315    63.9075   287.298
#         small_sh   27.340   32.8650    47.89785   38.5825    54.0850   358.540
#   small_sh_fastd    7.059    9.5050    13.49250   11.7795    15.6235    44.970
#       medium_md5 2506.346 2807.0950  2996.68143 2906.1890  3101.2860  9120.997
#        medium_sh   85.674  107.0095   131.44696  119.3410   136.6605  1072.424
#  medium_sh_fastd   75.845   92.1855   107.01148  104.1155   113.3485   526.869
#         large_sh 7650.311 8428.8285  8948.79861 8484.8885  8869.0875 16083.449
#   large_sh_fastd 8553.496 9628.2910 10131.64079 9681.3235 10022.3025 16999.323
```

**Comment by randy3k** [comment]
Thanks.

I have updated to algorithm to spookyhash 526a598.

``` r
d <- collections::dict()
key <- "a"
key1 <- 1L
key2 <- 1:1e5
key3 <- 1:1e7
d$set(key, 1)$set(key1, 1)$set(key2, 1)$set(key3, 1)

microbenchmark::microbenchmark(
  d$get(key),
  d$get(key1),
  d$get(key2),
  d$get(key3)
)
#> Unit: microseconds
#>         expr      min        lq       mean    median        uq      max neval
#>   d$get(key)    1.185    1.9590    5.26589    2.5055    4.4255  104.915   100
#>  d$get(key1)   36.660   42.3390   68.31933   50.4305   88.1845  192.542   100
#>  d$get(key2)   69.379   78.4575  105.41004   87.6580  130.7165  278.108   100
#>  d$get(key3) 3986.287 4133.4970 4640.62293 4456.9135 4958.9030 7092.316   100
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by tdeenes** [comment]
Thanks again for the quick update.

A side note: it seems `digest` does not utilize the ALTREP representation of the sequence, whereas `fastdigest` does:
```r
v1 <- 1:1e1
v6 <- 1:1e6
v1 <- 1:1e1
v6 <- 1:1e6
microbenchmark::microbenchmark(
  s1 = serialize(v1, NULL),
  s6 = serialize(v6, NULL),
  f1 = fastdigest::fastdigest(v1),
  f6 = fastdigest::fastdigest(v6),
  d1 = digest::digest(v1, algo = "spookyhash"),
  d6 = digest::digest(v6, algo = "spookyhash"),
  times = 1e4
)
# Unit: microseconds
#  expr     min       lq       mean   median       uq      max neval
#    s1   2.219   3.0520   3.963971   3.5160   3.9875  139.947 10000
#    s6   2.195   3.0330   4.403455   3.5220   4.0030 2139.431 10000
#    f1  10.257  11.5165  13.983922  12.4450  13.6245 2092.070 10000
#    f6  10.376  11.5855  14.000500  12.5865  13.7360 1780.209 10000
#    d1  27.497  30.0400  36.033242  31.2200  33.9990 2503.947 10000
#    d6 290.258 296.1715 349.444215 301.9275 352.8780 2530.813 10000
```

**Comment by randy3k** [comment]
I am not sure about switching to `fastdigest` because it has not been updated for a while.

**Comment by randy3k** [comment]
In the end, I have decided to switch to `fastdigest`. Its speed is unbeatable, especially that it handles ALTREP well.


``` r
d <- collections::dict()
key <- "a"
key1 <- 1L
key2 <- 1:1e5
key3 <- 1:1e7
d$set(key, 1)$set(key1, 1)$set(key2, 1)$set(key3, 1)

microbenchmark::microbenchmark(
  d$get(key),
  d$get(key1),
  d$get(key2),
  d$get(key3)
)
#> Unit: microseconds
#>         expr    min      lq     mean  median      uq    max neval
#>   d$get(key)  1.120  1.6020  1.59027  1.6625  1.7020  2.209   100
#>  d$get(key1) 12.010 14.8960 16.30504 15.2135 16.6115 42.794   100
#>  d$get(key2) 11.605 15.3085 16.81258 15.5745 16.0425 99.417   100
#>  d$get(key3) 12.027 15.3940 16.49164 15.7290 16.7510 35.493   100
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by randy3k** [comment]
Another update, I have implemented [xxhash](https://github.com/Cyan4973/xxHash) algorithm (thanks `fastdigest` to teach me how to do it.)

It is 3x of the `fastdigest` approach (mostly because we call the c routine directly).

``` r
d <- collections::dict()
key <- "a"
key1 <- 1L
key2 <- 1:1e5
key3 <- 1:1e7
key4 <- runif(1e5)
d$set(key, 1)$set(key1, 1)$set(key2, 1)$set(key3, 1)$set(key4, 1)

microbenchmark::microbenchmark(
  d$get(key),
  d$get(key1),
  d$get(key2),
  d$get(key3),
  d$get(key4)
)
#> Unit: microseconds
#>         expr    min      lq     mean  median      uq     max neval
#>   d$get(key)  1.111  1.3240  2.05636  1.4305  1.6140  34.623   100
#>  d$get(key1)  2.210  4.8710  5.65750  5.4000  6.4795  23.220   100
#>  d$get(key2)  2.619  4.0800  6.81553  5.9685  7.0700  54.901   100
#>  d$get(key3)  2.788  5.5960  6.21549  6.0035  6.8315  19.961   100
#>  d$get(key4) 45.318 48.3895 52.69087 48.8530 50.0530 154.421   100
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by tdeenes** [comment]
Very nice. Probably we should run some tests to test the collision rates just to make sure that nothing went wrong.

It would be definitely helpful to expose that function both at the C and the R level, or probably create an R package for it. (I am sure Dirk [Eddelbuettel] would argue against creating an other digest package, but I think the digest pkg should be refactored so that it only provides an API, and the algos themselves reside in separate packages. But this is maybe an other story.)

My use case is that I want to avoid repeated hashing of the same object. So I either want to pre-hash the object before using it as a key, or want be able to get back the internal representation of the key once it has been added to the key-value store. 

E.g.: 
```r
d <- collections::dict()
obj <- as.list(1:3)
# return the internal representation of an object if 
# it is entered as a key to `d`;
# returns the memory address of `object` if it is an environment, 
# or its internal hash otherwise
obj_hash <- d$key(object)
# the vectorized version; returns the same length as the length 
# of `object`
obj_hashes <- d$key(object, vectorized = TRUE)
# It is not really required for my use case, but might be still helpful: 
# return the digest of the object (so it returns the 'real' hash, no 
# matter if it is an environment)
e <- new.env()
e$a <- 1
e_digest <- d$digest(e, vectorized = FALSE) 

All relevant methods could receive a "hash" argument:
# do not return the keys, only their hashes
d$keys(hash = TRUE)
# check by hash
d$has(obj_hash, hash = TRUE)
# get by hash
d$get(obj_hash, hash = TRUE)
```

What do you think?

**Comment by randy3k** [comment]
```
d$get(obj_hash, hash = TRUE)
```

But it wouldn’t work if there are collisions, isn’t it?

**Comment by tdeenes** [comment]
If there is a collision, the dictionary is corrupted for the original key, too. Or am I missing something?

That is, if `d$key(object1) == d$key(object2) && !identical(object1, object2)` is `TRUE`, `d$set(object1, TRUE)$set(object2, FALSE)$get(object1)` will return (erroneously) `FALSE`.

**Comment by randy3k** [comment]
`d$set(object1, TRUE)$set(object2, FALSE)$get(object1)` will return the correct value `TRUE` even if the hash for `object1` and `object2` ar the same.

See for example https://en.wikipedia.org/wiki/Hash_table#Separate_chaining

**Comment by tdeenes** [comment]
Thanks for the enlightment, I was not aware of separate chaining. But this also means that we can detect if there are more entries for the same hash, can't we? In this case, an error can be thrown as a simple safeguard action.

**Comment by randy3k** [comment]
I think pre-hashing is really out of the scope of collections. It is the decision of the user if they want to pre-hash the keys and use the hashes as keys instead.

**Comment by tdeenes** [comment]
No worries, it is absolutely fine if you keep it this way.

**Comment by randy3k** [comment]
0.3.4 is on the way.
