### ISSUE TITLE
Is there a convenience function for merging dictionaries?

### ISSUE THREAD

**Issue by travis-leith** [randy3k/collections#18]
Maybe something like `dict(dict1, dict2, dict3, ...)`

Collisions can be handled by taking either the first or last value for the same key.

**Comment by randy3k** [comment]
There is a `update` method for the `dict` objects. You may want to check it out.

**Comment by travis-leith** [comment]
Is it correct to say that my pseudo code above would be properly translated as the following?

```R
dictMerged <- dict1
dictMerged$update(dict2)
dictMerged$update(dict3)
```

**Comment by randy3k** [comment]
You could chain the operations together. `d1$update(d2)$update(d3)`. However notice that `d1` is modified in place.
