### ISSUE TITLE
Implement reset() or clear()

### ISSUE THREAD

**Issue by krlmlr** [randy3k/collections#3]
Would you support these methods, at least for `Queue` or `Stack`?

Thanks for the package!

**Comment by randy3k** [comment]
Definitely, I might be able to do it tomorrow or the coming weekend.

I am glad that someone finds that it's useful.

**Comment by randy3k** [comment]
v0.1.4 is now on cran.

**Comment by krlmlr** [comment]
Thanks a lot!
