### ISSUE TITLE
Initialiser for Dict runs incredibly slowly

### ISSUE THREAD

**Issue by UnclAlDeveloper** [randy3k/collections#6]
I haven't tried any of the other collection objects, just the Dict.  To initialise it with a list of about 100,000 string to integer key pairs took about a minute.  However this only seem to happen when trying to initialise the Dict when initially creating it.  If a create an empty Dict and use a for loop to populate the key pairs one at a time by using set, this dropped down to about 4 seconds.

**Comment by randy3k** [comment]
It’s because the initialiser is making a copy of the keys: https://github.com/randy3k/collections/blob/master/R/dict.R#L52.

I think we could avoid this by moving the code to c.

**Comment by randy3k** [comment]
It turns out that the slowness is due to the string index, I have pushed a commit ef574c9 and it should improve the speed by some order of magnitude.

**Comment by randy3k** [comment]
v0.2.2 is released.

**Comment by randy3k** [comment]
I found a serious bug in the current version v0.2.2. If you need `Dict()`, please use the master branch for the moment.
