### ISSUE TITLE
Error: C stack usage  7969440 is too close to the limit

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/collections#8]
Printing the storage object (e.g. `last` in `deque`) or call `saveRDS` on the container objects produces error.

```r
d <- collections::deque()
d$push(1)
d$push(2)
d$push(3)
```

```r
d$last
```

<img width="661" alt="image" src="https://user-images.githubusercontent.com/4662568/80609327-8756ca80-8a6a-11ea-9739-7c2387714801.png">

```r
saveRDS(d, "test.rds")
```

```
Error: C stack usage  7969440 is too close to the limit
```

It seems that some containers use R data structures to implement the algorithms. I'm wondering if such error could be eliminated somehow?

**Comment by randy3k** [comment]
Thanks for raising it. I beleive it should only affect `deque` and `ordered_dict` (since `ordered_dict` uses `deque`).

We essentially implemented a doubly linked list on top of R's pairlist. 

It was something like it:
```c
SEXP foo() {
    SEXP x = Rf_cons(Rf_ScalarInteger(1), R_NilValue);
    SEXP y = Rf_cons(x, R_NilValue);
    SETCDR(x, y);
    return x;
}
```

I guess there are self-referencing issues while you are trying to print it or serialize it. Let me think of a work around.

**Comment by randy3k** [comment]
Perhaps we need to use two seqparate linked lists.

**Comment by randy3k** [comment]
In the end, I switched to external pointers to handle the self-referencing problem.

**Comment by renkun-ken** [comment]
Thanks for the nice work!

**Comment by randy3k** [comment]
By the way, serialization doesn't work very well in general.

Try to save the objects by other means if possible.

```r
library(lobstr)
x <- rnorm(100000)
obj_size(x)
#> 800,048 B
obj_size(list(x, x))
#> 800,112 B
obj_size(unserialize(serialize(list(x, x), NULL)))
#> 1,600,160 B
```

**Comment by randy3k** [comment]
0.3.1 is out
